const settingsScreens = require('./src/tailwind/tailwind.settings.screens')
const settingsFontSizes = require('./src/tailwind/tailwind.settings.fontSizes')

module.exports = {
  purge: ['./src/**/*.{js,jsx}'],
  mode: 'jit',
  important: true,
  theme: {
    screens: settingsScreens,
    spacing: {
      px: '1px',
      '4': '4px',
      '6': '6px',
      0: '.5em',
      1: '1em',
      2: '1.5em',
      8: '2rem',
      16: '1rem',
      24: '1.5rem',
      32: '2rem',
      40: '2.5rem',
      48: '3rem',
      56: '3.5rem',
      64: '4rem',
      72: '4.5rem',
      80: '5rem',
      96: '5.5rem',
      104: '6rem',
      112: '6.5rem',
      120: '7rem',
    },
    maxWidth: {
      none: 'none',
      0: '0rem',
      xs: '20rem',
      sm: '28rem',
      md: '36rem',
      lg: '44rem',
      xl: '52rem',
      '2xl': '60rem',
      '3xl': '68rem',
      '4xl': '76rem',
      '5xl': '84rem',
      '6xl': '90rem',
      '7xl': '100rem',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      prose: '65ch'
    },
    fontSize: settingsFontSizes,
    colors: {
      blue: 'rgb(54, 163, 255)',
      black: 'rgb(31, 32, 40)',
      red: 'rgb(255, 69, 69)',
      gray: 'rgb(185, 185, 195)',
      darkGray: '#1f2028',
      dark: '#2e3039',
      white: 'rgb(247, 247, 247)',
      lightGray: 'rgb(169, 173, 193)',
      ZhenZhuBaiPearl : "rgb(249, 249, 251)",
      ZhenZhuBaiPearl2 : "rgb(66, 51, 211)",
      ZhenZhuBaiPearl3 : "rgb(7, 3, 70)",
      GrapeHyacinth : "rgb(147, 150, 175)",
      NightBlue : "rgb(115, 119, 145)",
      CharcoalDust : "rgb(47, 57, 211)",
      IrisEyes : "rgb(28, 32, 66)",
      PalatinateBlue : "rgb(22, 26, 51)",
      KonkikyoBlue : "rgb(15, 18, 38)",
      HeiSeBlack : "rgb(17, 160, 210)",
      Corbeau : "rgb(239, 167, 88)",
      CyanBlue : "rgb(255, 115, 74)",
      BrassTrumpet : "rgb(255, 82, 51)",
      PinkishOrange : "rgba(255, 255, 255, 0.75)",
      PortlandOrange : "rgb(255, 255, 255)",
      White : "rgb(249, 249, 249)",
      White2 : "rgba(248, 248, 248, 0.85)",
      Snowflake : "rgb(240, 240, 240)",
      deadlydepths: "rgb(23, 12, 62)",
      nightblue: "rgb(7, 3, 70)",
      palatinateblue: "rgb(46, 58, 213)",
      cyanblue: "rgb(17, 160, 210)",
      lighthouse: "rgb(241, 247, 245)",
      brasstrumpet: "rgb(239, 167, 88)",
      bruschettatomato: "rgb(255, 100, 74)",
    },
    textColor: (theme) => ({
      'primary': theme('colors.red'),
      'secondary': theme('colors.white'),
      ...theme('colors'),
    }),
    fontFamily: {
      merriweather: ['Merriweather', 'serif'],
      murecho: ['Murecho', 'sans-serif'],
    },
    fontWeight: {
      thin: '100',
      extralight: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900',
    },
    borderColor: theme => ({
      ...theme('colors'),
      DEFAULT: theme('colors.white'),
    }),
    typography: (theme) => ({
      DEFAULT: {
        css: {
          color: theme('colors.white'),
          h1: {
            fontFamily: 'Merriweather',
            color: theme('colors.ZhenZhuBaiPearl3'),
            fontSize: theme('fontSize.7xl'),
            lineHeight: '1',
            marginBottom: theme('spacing.24'),
          },
          h2: {
            fontFamily: 'Merriweather',
            color: theme('colors.ZhenZhuBaiPearl3'),
            fontSize: theme('fontSize.4xl'),
            lineHeight: '1',
            marginBottom: theme('spacing.16'),
          },
          h3: {
            fontFamily: 'Merriweather',
            color: theme('colors.ZhenZhuBaiPearl3'),
            fontSize: theme('fontSize.lg'),
            lineHeight: '1.2',
            marginBottom: theme('spacing.8'),
          },
          h4: {
            fontFamily: 'Merriweather',
            color: theme('colors.ZhenZhuBaiPearl3'),
            fontSize: theme('fontSize.base'),
            lineHeight: '1.2',
            marginBottom: theme('spacing.8'),
          },
          h5: {
           fontFamily: 'Merriweather',
           color: theme('colors.ZhenZhuBaiPearl3'),
          },
          h6: {
            fontFamily: 'Merriweather',
            color: theme('colors.white'),
          },
          p: {
            fontFamily: 'murecho',
            color: theme('colors.NightBlue'),
            fontSize: theme('fontSize.base'),
            lineHeight: '1.4',
          },
          ul: {
            fontSize: theme('fontSize.base'),
            fontFamily: 'murecho',
            color: theme('colors.NightBlue'),
            lineHeight: '1.7',
          },
          li: {
          },
          span: {
            fontFamily: 'murecho',
          },
          strong: {
            color: theme('colors.nightblue'),
          },
          a: {
            fontFamily: 'murecho',
            color: theme('colors.nightblue'),
            fontWeight: 'bold',
            '&:hover': {
              color: theme('colors.nightblue'),
            },
          },
        },
      },
    }),
    extend: {
      backgroundColor: (theme) =>({
        ...theme('colors'),
      }),
    },
  },
  variants: {
  },
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/typography'),
  ],
}
